import WriteProposal from "@/components/WriteProposal";
import Response from "@/components/Response";
import Head from "next/head";
import { useContext } from "react";
import { Toaster } from "react-hot-toast";
import { AppContext } from "./_app";

export default function Home() {
  const { currentStep, setCurrentStep } = useContext(AppContext);

  return (
    <>
      <Head>
        <title>Upwrite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex w-full min-h-screen gap-8 pr-4 pl-28 overflow-hidden">
        <Toaster containerClassName="text-sm" />

        {currentStep === 1 ? (
          <WriteProposal setCurrentStep={setCurrentStep} />
        ) : (
          <Response />
        )}
      </div>
    </>
  );
}
