import WriteProposal from "@/components/WriteProposal";
import Response from "@/components/Response";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Upwritten</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <h1>Say goodbye to proposal struggles</h1> */}

      <div className="flex w-full h-screen gap-8 px-8 mt-28 mb-12">
        {/* Write Proposal */}
        <WriteProposal />
        <div className="w-1 h-full bg-[#2D4263]"></div>
        {/* Ai Response */}
        <Response />
      </div>
    </>
  );
}
